#!/usr/bin/env python3
"""
tiled_export.py -- Convert a Tiled JSON map to a C header for the PS1 engine.

Tile layers   -> static const uint8_t  <PREFIX>_<LAYER>_tiles[]
Map constants -> #define <PREFIX>_MAP_W / _MAP_H / _TILE_SIZE / _TILES_PER_ROW

Usage:
    python tiled_export.py level.json [options]

Options:
    --prefix NAME    C identifier prefix  (default: derived from filename)
    --output FILE    Write to FILE instead of stdout
    --tile-size N    Override tile size in pixels  (default: from Tiled map)

Example:
    python tiled_export.py levels/world1.json --prefix WORLD1 --output src/world1_map.h

Then in your scene factory:
    #include "world1_map.h"
    tm->tiles         = WORLD1_BACKGROUND_tiles;
    tm->map_w         = WORLD1_MAP_W;
    tm->map_h         = WORLD1_MAP_H;
    tm->tile_size     = WORLD1_TILE_SIZE;
    tm->tiles_per_row = WORLD1_TILES_PER_ROW;

Index mapping
-------------
Tiled GID 0          -> engine index 0  (transparent -- TileMap skips it)
Tiled GID firstgid+N -> engine index N  (0-based index into tileset)
"""

import json
import sys
import os
import argparse
from datetime import datetime, timezone

# -- Tiled GID flags (top 3 bits = flip/rotate -- mask them off) --------------
_FLIP_MASK = 0x1FFFFFFF


def _to_c_ident(s):
    """Convert an arbitrary string to a safe uppercase C identifier fragment."""
    return "".join(c if c.isalnum() else "_" for c in s).upper().strip("_")


def _warn(msg):
    print(f"WARNING: {msg}", file=sys.stderr)


def convert(map_path, prefix=None, tile_size_override=None):
    """
    Parse a Tiled JSON file and return the generated C header as a string.

    Parameters
    ----------
    map_path : str
        Path to the .json file exported by Tiled.
    prefix : str | None
        C identifier prefix for all generated symbols.  Derived from the
        filename if None.
    tile_size_override : int | None
        Force a specific tile_size value; otherwise taken from the map.

    Returns
    -------
    str  -- complete contents of the .h file.
    """
    with open(map_path, "r", encoding="utf-8") as f:
        m = json.load(f)

    if m.get("orientation") != "orthogonal":
        _warn(f"map orientation is '{m.get('orientation')}'; engine only supports orthogonal.")

    if prefix is None:
        prefix = _to_c_ident(os.path.splitext(os.path.basename(map_path))[0])

    map_w  = m["width"]
    map_h  = m["height"]
    tile_w = m.get("tilewidth",  16)
    tile_h = m.get("tileheight", 16)

    if tile_w != tile_h:
        _warn(f"non-square tiles ({tile_w}x{tile_h}) -- engine tile_size is a single value; using width ({tile_w}).")
    tile_size = tile_size_override if tile_size_override else tile_w

    # -- Tileset ---------------------------------------------------------------
    tilesets = m.get("tilesets", [])
    if not tilesets:
        _warn("no tilesets found in map -- tile indices will be raw GIDs.")
        first_gid     = 1
        tiles_per_row = 0
    else:
        if len(tilesets) > 1:
            _warn(
                f"map references {len(tilesets)} tilesets; only the first is used. "
                "Merge all tilesets into one atlas before exporting."
            )
        ts            = tilesets[0]
        first_gid     = ts.get("firstgid", 1)
        tiles_per_row = ts.get("columns", 0)

    # -- Collect tile layers only ---------------------------------------------
    tile_layers = []
    for layer in m.get("layers", []):
        ltype = layer.get("type")
        if ltype == "tilelayer":
            tile_layers.append(layer)
        elif ltype == "group":
            _warn(f"group layer '{layer.get('name')}' is not expanded -- flatten groups in Tiled before exporting.")
        # object layers and image layers are ignored

    # -- Output buffer --------------------------------------------------------
    lines = []
    ts_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    guard = f"{prefix}_MAP_H"
    lines += [
        f"/* Auto-generated by tiled_export.py  --  {ts_str} */",
        f"/* Source: {os.path.basename(map_path)} */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
    ]

    # -- Map-level constants --------------------------------------------------
    lines += [
        "/* Map dimensions */",
        f"#define {prefix}_MAP_W         {map_w}",
        f"#define {prefix}_MAP_H         {map_h}",
        f"#define {prefix}_TILE_SIZE     {tile_size}",
        f"#define {prefix}_TILES_PER_ROW {tiles_per_row}",
        "",
        "/* World pixel size of the full map */",
        f"#define {prefix}_MAP_PX_W  ({prefix}_MAP_W  * {prefix}_TILE_SIZE)",
        f"#define {prefix}_MAP_PX_H  ({prefix}_MAP_H  * {prefix}_TILE_SIZE)",
        "",
    ]

    # -- Tile layers ----------------------------------------------------------
    for layer in tile_layers:
        if not layer.get("visible", True):
            _warn(f"tile layer '{layer.get('name')}' is hidden in Tiled -- exporting anyway.")

        layer_id = _to_c_ident(layer.get("name", "layer"))
        raw      = layer.get("data", [])

        if len(raw) != map_w * map_h:
            _warn(
                f"tile layer '{layer.get('name')}' has {len(raw)} entries, "
                f"expected {map_w * map_h}; skipping."
            )
            continue

        # GID -> engine tile index
        # Tiled:  0 = empty,  firstgid+N = Nth tile in tileset (0-based)
        # Engine: 0 = atlas tile 0,  1 = atlas tile 1 ...
        converted = []
        for raw_gid in raw:
            gid = raw_gid & _FLIP_MASK
            if gid == 0:
                converted.append(0)
            else:
                idx = gid - first_gid   # 0-based engine index
                if not (0 <= idx <= 255):
                    _warn(f"tile GID {gid} -> engine index {idx} is outside uint8_t range; clamping.")
                    idx = max(0, min(255, idx))
                converted.append(idx)

        lines.append(f"/* Tile layer: '{layer.get('name', layer_id)}' */")
        lines.append(
            f"static const uint8_t {prefix}_{layer_id}_tiles"
            f"[{prefix}_MAP_H * {prefix}_MAP_W] = {{"
        )

        for row in range(map_h):
            row_vals = converted[row * map_w : (row + 1) * map_w]
            # Group values in sets of 10 for readability
            chunks = [row_vals[i:i+10] for i in range(0, len(row_vals), 10)]
            chunk_strs = [", ".join(f"{v:3d}" for v in c) for c in chunks]
            row_str = ",  ".join(chunk_strs)
            lines.append(f"    {row_str},  /* row {row} */")

        lines += ["};", ""]

    # -- Footer ---------------------------------------------------------------
    lines += [
        f"#endif /* {guard} */",
        "",
    ]

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Convert a Tiled JSON map to a C header for the PS1 engine.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("input",
        help="Path to the Tiled .json map file")
    parser.add_argument("--prefix", default=None,
        help="C identifier prefix (default: derived from filename)")
    parser.add_argument("--output", default=None,
        help="Output .h file path (default: stdout)")
    parser.add_argument("--tile-size", type=int, default=None, dest="tile_size",
        help="Override tile size in pixels (default: from Tiled map)")
    args = parser.parse_args()

    output = convert(args.input, prefix=args.prefix, tile_size_override=args.tile_size)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(output)
        print(f"Written to {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(output)


if __name__ == "__main__":
    main()
